// app/components/HighlightedText.vue
<script setup lang="ts">
interface Seg {
  h: boolean;
  t: string;
}

const props = defineProps<{ query?: string; text: string }>();

const segments = computed<Seg[]>(() => {
  const q = props.query?.trim();
  if (!q) return [{ h: false, t: props.text }];

  const out: Seg[] = [];
  const hay = props.text.toLocaleLowerCase();
  const needle = q.toLocaleLowerCase();
  let cur = 0;
  let m = hay.indexOf(needle);

  while (m !== -1) {
    if (m > cur) out.push({ h: false, t: props.text.slice(cur, m) });
    const end = m + q.length;
    out.push({ h: true, t: props.text.slice(m, end) });
    cur = end;
    m = hay.indexOf(needle, cur);
  }

  if (cur < props.text.length) out.push({ h: false, t: props.text.slice(cur) });
  return out.length ? out : [{ h: false, t: props.text }];
});
</script>

<template>
  <template v-for="(s, i) in segments" :key="i">
    <mark v-if="s.h" class="bg-primary/20 text-primary">{{ s.t }}</mark>
    <template v-else>{{ s.t }}</template>
  </template>
</template>

// components/HighlightedText.tsx
import { useMemo } from "react";

interface Seg {
  h: boolean;
  t: string;
}

export function HighlightedText({ text, query }: { text: string; query?: string }) {
  const segments = useMemo<Seg[]>(() => {
    const q = query?.trim();
    if (!q) return [{ h: false, t: text }];

    const out: Seg[] = [];
    const hay = text.toLocaleLowerCase();
    const needle = q.toLocaleLowerCase();
    let cur = 0;
    let m = hay.indexOf(needle);

    while (m !== -1) {
      if (m > cur) out.push({ h: false, t: text.slice(cur, m) });
      const end = m + q.length;
      out.push({ h: true, t: text.slice(m, end) });
      cur = end;
      m = hay.indexOf(needle, cur);
    }

    if (cur < text.length) out.push({ h: false, t: text.slice(cur) });
    return out.length ? out : [{ h: false, t: text }];
  }, [text, query]);

  return segments.map((s, i) =>
    s.h ? (
      <mark key={i} className="rounded-sm bg-kumo-info-tint text-kumo-link">
        {s.t}
      </mark>
    ) : (
      <span key={i}>{s.t}</span>
    ),
  );
}
