// app/components/UserMenu.vue
<script setup lang="ts">
const { authenticated, user, pending, login, logout } = useAuth();
</script>

<template>
  <div class="flex items-center gap-2">
    <div v-if="pending && !user" class="size-8 animate-pulse rounded-full bg-darkless" />

    <template v-else-if="authenticated && user">
      <div
        class="flex items-center gap-2 rounded-lg border border-border bg-dark px-2 py-1.5"
        :title="user.login"
      >
        <img
          v-if="user.avatarUrl"
          :src="user.avatarUrl"
          :alt="user.login"
          class="size-6 rounded-full"
          width="24"
          height="24"
        />
        <span class="hidden max-w-28 truncate text-sm text-snow sm:inline">{{ user.login }}</span>
      </div>
      <button
        type="button"
        class="cursor-pointer rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted transition-colors hover:border-muted hover:text-snow"
        @click="logout()"
      >
        Sign out
      </button>
    </template>

    <button
      v-else
      type="button"
      class="flex cursor-pointer items-center gap-1.5 rounded-lg border border-border bg-dark px-3 py-2 text-sm text-snow transition-colors hover:bg-darkless"
      @click="login()"
    >
      <Icon name="simple-icons:github" size="1rem" />
      <span class="hidden sm:inline">Sign in with GitHub</span>
      <span class="sm:hidden">Sign in</span>
    </button>
  </div>
</template>

// components/UserMenu.tsx
"use client";

import { Button, DropdownMenu } from "@cloudflare/kumo";
import { CaretDownIcon, GithubLogoIcon, SignOutIcon } from "@phosphor-icons/react";
import { useAuth } from "@/lib/client/auth";

export function UserMenu() {
  const { authenticated, user, pending, login, logout } = useAuth();

  if (pending && !user) {
    return <div className="size-9 animate-pulse rounded-lg bg-kumo-tint" aria-hidden />;
  }

  if (authenticated && user) {
    return (
      <DropdownMenu>
        <DropdownMenu.Trigger
          render={
            <Button variant="secondary" aria-label={`Account menu for ${user.login}`}>
              {user.avatarUrl && (
                // oxlint-disable-next-line nextjs/no-img-element -- tiny avatar, no optimisation needed
                <img
                  src={user.avatarUrl}
                  alt=""
                  width={20}
                  height={20}
                  className="size-5 rounded-full"
                />
              )}
              <span className="hidden max-w-28 truncate sm:inline">{user.login}</span>
              <CaretDownIcon className="size-3.5 text-kumo-subtle" />
            </Button>
          }
        />
        <DropdownMenu.Content align="end">
          <DropdownMenu.Label>Signed in as @{user.login}</DropdownMenu.Label>
          <DropdownMenu.LinkItem
            href={`https://github.com/${user.login}`}
            target="_blank"
            icon={GithubLogoIcon}
          >
            GitHub profile
          </DropdownMenu.LinkItem>
          <DropdownMenu.Separator />
          <DropdownMenu.Item icon={SignOutIcon} onClick={() => void logout()}>
            Sign out
          </DropdownMenu.Item>
        </DropdownMenu.Content>
      </DropdownMenu>
    );
  }

  return (
    <Button variant="secondary" icon={GithubLogoIcon} onClick={() => login()}>
      <span className="hidden sm:inline">Sign in with GitHub</span>
      <span className="sm:hidden">Sign in</span>
    </Button>
  );
}
